
DATA_KEYWORDS = {
    "Account Information": [
        "name",
        "email",
        "email address",
        "phone number",
        "account information",
        "profile information",
        "user identifier",
        "unique identifier",
        "username",
        "account",
    ],

    "Payment Information": [
        "payment",
        "billing",
        "credit card",
        "transaction",
        "invoice",
        "subscription",
    ],

    "User Content": [
        "prompt",
        "input",
        "inputs",
        "output",
        "outputs",
        "conversation",
        "chat",
        "message",
        "messages",
        "uploaded file",
        "uploaded files",
        "file upload",
        "attachment",
        "feedback",
        "user content",
    ],

    "Device and Technical Data": [
        "ip address",
        "device",
        "device type",
        "browser",
        "operating system",
        "mobile network",
        "logs",
        "error logs",
        "troubleshooting logs",
        "usage data",
        "diagnostic",
        "diagnostics",
    ],

    "Location Data": [
        "location",
        "region",
        "country",
        "time zone",
        "timezone",
        "geolocation",
    ],

    "Cookies and Tracking": [
        "cookie",
        "cookies",
        "analytics",
        "advertising identifier",
        "advertising identifiers",
        "tracking",
        "marketing",
        "authentication cookies",
    ],

    "Security and Safety Data": [
        "safety",
        "trust and safety",
        "abuse",
        "fraud",
        "security",
        "moderation",
        "violation",
        "classifier",
    ],

    "Retention and Storage": [
        "retain",
        "retention",
        "store",
        "stored",
        "storage",
        "delete",
        "deleted",
        "deletion",
        "30 days",
        "5 years",
        "7 years",
    ],

    "Model Improvement and Training": [
        "model improvement",
        "improve our services",
        "improve our products",
        "training",
        "train",
        "fine-tune",
        "fine tuning",
        "evaluation",
        "quality improvement",
    ],

    "Third Party Sharing": [
        "third party",
        "third-party",
        "service provider",
        "vendor",
        "partner",
        "share",
        "sharing",
        "disclose",
        "transfer",
    ],
}